---
- name: (Ubuntu) vcs packages...
  when: ansible_distribution == "Ubuntu"
  environment: proxy_env
  apt: name={{ item }}
  with_items:
    - git
    - git-doc
    - git-svn
    - git-flow
    - subversion
    - mercurial
    - tortoisehg
    - hgsubversion
    - svnkit
    - cvs
    - kdiff3

- name: (Fedora) vcs packages...
  when: ansible_distribution == "Fedora"
  environment: proxy_env
  yum: name={{ item }}
  with_items:
    - git
    - gitflow
    - subversion
    - mercurial
    - svnkit-cli
    - cvs
    - kdiff3

- name: (RedHat) vcs packages...
  when: ansible_distribution == "RedHat"
  environment: proxy_env
  yum: name={{ item }}
  with_items:
    - git
    - subversion
    - mercurial
    - cvs


  
